#!/usr/bin/env bash

# region #! globals

PROJ_DIR="/home/bane/dev/deb-repo"
SWD=$(pwd)

#! task
TASK_FILE="${PROJ_DIR}/packages.built"

#! tests related
TEST_ENABLE=""
TEST_SAMPLES=1 # generate test samples during execution

# endregion

# region #! include

. ${PROJ_DIR}/bin/log-lib # exit, warning, info

. ${PROJ_DIR}/bin/test-lib # testing, samples, asserts support

. ${PROJ_DIR}/bin/tag-lib # tags functions
. ${PROJ_DIR}/bin/docker-lib # helpers for docker
. ${PROJ_DIR}/bin/task-lib # single task related
. ${PROJ_DIR}/bin/build-lib # build a bunch of task

# endregion

# region #! main
cd ${PROJ_DIR}

testInit

buildAll

cd $SWD
# endregion