#!/usr/bin/env bash

# region #! globals

#! test dir for asserts & samples
TEST_DIR="${PROJ_DIR}/tests"
TEST_V_SAMPLES="${TEST_DIR}/samples/version"
TEST_VR_SAMPLES="${TEST_DIR}/samples/version-req"

# endregion

# region #! funcs

# return true if global test mode enabled
isTestEnabled() {
  [[ -n TEST_ENABLE ]] && echo "1" || echo ""
}

isSamplesEnabled() {
  [[ -n TEST_SAMPLES ]] && echo "1" || echo ""
}

# initialize tests - files, variables, etc
testInit() {
  if [[ $(isTestEnabled) ]] || [[ $(isSamplesEnabled) ]]; then
    # [[ -d "$TEST_DIR" ]] && rm -r "$TEST_DIR"
    # mkdir "$TEST_DIR"
    if [[ $(isSamplesEnabled) ]]; then
      [[ -f "$TEST_V_SAMPLES" ]] && rm -f "$TEST_V_SAMPLES"
      touch "$TEST_V_SAMPLES"
      [[ -f "$TEST_VR_SAMPLES" ]] && rm -f "$TEST_VR_SAMPLES"
      touch "$TEST_VR_SAMPLES"
      # fixme: pre-generated samples
      cat "${TEST_VR_SAMPLES}-include" > "$TEST_VR_SAMPLES"
    fi
  fi
}

# define test asserts: testAsserts <func_name>
testAsserts() {
  return
}

# do fuction test
testFunc() {
  return
}

# add function to call trace
testCallTrace() {
  return
}

# add to version samples: testAddToVersionSamples <cond> <@version>
testAddToVersionSamples() {
  [[ $(isSamplesEnabled) ]] || return
  local cond="$1"
  shift
  echo "$cond" "$@" >> "$TEST_V_SAMPLES"
}

# add to version samples: testAddToVersionSamples <vr1> <vr2> <vres> <vcode>
testAddToVReqSamples() {
  [[ $(isSamplesEnabled) ]] || return
  local res="$1;$2;$3;$4"
  res="${res// /'&'}"
  echo "$res" >> "$TEST_VR_SAMPLES"
}

# endregion